### ISSUE TITLE
Feature: User can 

### ISSUE THREAD

**Issue by brendan-kormos** [brendan-kormos/ajax-project#1]
## ⚙️ Feature

> ##### View a list of rocket's and some details

## 📐 Functionality

> ##### View a list of rocket entries with a serial number, picture, and description attached.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/brendan-kormos/ajax-project/assets/44518726/133e15d1-bec5-463f-b873-55fa4e2c5e24)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] Format space for a nav bar at the top of the screen
- [ ]  Create a hamburger button and place it on the far left of the nav bar
- [ ] Create a "home" button and place it to the right of the hamburger button within the nav bar
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Create a new div for the list of entries that will be displayed
- [ ] Create each entry 
  - [ ] Create img element that will display the "image_url" value from the launchers api call
  - [ ] Create a header with a header element that will display the "serial_number" value from the launchers api call
  - [ ] Create a line to separate the header from the body
  - [ ] Create a p element for the body with the "details" value as it's content from the launchers api call
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
