### ISSUE TITLE
Feature: User can click on an entry to view more details

### ISSUE THREAD

**Issue by brendan-kormos** [brendan-kormos/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view rocket details 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When clicking on the rocket entry, you will be shown extra details about the rocket you clicked

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/brendan-kormos/ajax-project/assets/44518726/d4e8a9cc-bf50-482a-b265-54bf7761070e)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] Clone the entry frame and make it fill a larger portion of the page, there should only be one entry on the page
- [ ] Create a new div under the text for  the details that will be displayed
- [ ] When an entry is clicked from the home screen, pull from api and get the details about the entry
- [ ] Display the important details about the rocket, name, description, and launcher info
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
