### ISSUE TITLE
Feature: User can Save entries

### ISSUE THREAD

**Issue by brendan-kormos** [brendan-kormos/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Save entry to be tracked and viewed later

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will see a heart icon on the top right of an entry and click on it to save the rocket's information 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/brendan-kormos/ajax-project/assets/44518726/d942796d-268d-43a4-baf1-8e76a29b0f04)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] Find "heart" icon from fontawesome
- [ ] Place icon in the top right of an entry
- [ ] When clicked,
  - [ ] Fill heart icon with the color red
  - [ ] Access the localstorage key "launcher-data-ajax-project" and save the data to the "saves" array
- [ ] Every time entries are loaded on the home page, fill all heart icons with the color red that are saved in data.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
