### ISSUE TITLE
Feature: User can Remove save from data

### ISSUE THREAD

**Issue by brendan-kormos** [brendan-kormos/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Remove entry from saved

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When clicking on the heart icon of an entry that is already saved, you will remove the entry from your saved data

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/brendan-kormos/ajax-project/assets/44518726/adb103b0-c3b0-416b-b4cb-b9a2ae8d4f6d)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] When clicking an entry's hard icon that is filled in red
  - [ ] Remove save from data
  - [ ] Remove the filled color from the icon, likely from changing font to the stroke only version of the heart icon
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
