### ISSUE TITLE
Feature: User can View saved entries

### ISSUE THREAD

**Issue by brendan-kormos** [brendan-kormos/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to view a list of the entries saved as if it were the home screen

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When clicking on the saves button in the nav bar, content on the screen will be filled with a list of saved entries

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/brendan-kormos/ajax-project/assets/44518726/ee4ead19-275d-45e4-8940-883ad53e51d5)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create a new, smaller button next to the HOME button in the nav bar named "SAVES"
- [ ] When the save button is clicked
  - [ ] Swap the home and saves buttons and their styling
  - [ ] Remove all of the content on the page and load entries from saved data
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
