### ISSUE TITLE
Feature: User can Search info

### ISSUE THREAD

**Issue by brendan-kormos** [brendan-kormos/ajax-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Search for specific information about rockets

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view and use a search bar to show rockets that contain specific information

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/brendan-kormos/ajax-project/assets/44518726/0bf1f027-22f2-46fc-83f9-9b8278cf708c)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create a search bar as shown in the figma design
- [ ] When clicking or pressing enter while focused on search bar
  - [ ] make a search api request for the provided parameters
  - [ ] Remove all content and display the entries that were received from the api request
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
